### PR TITLE
Haya

### PR DESCRIPTION
**Pull request by hayatariq**
use cases adhere to dependency rule! (i think). Just songById left. I also added a loggedInUser in the FileUserDAO if you guys want to check that out. I was thinking when the user logs in, the baseview is initialized and the outputdata of the log in use case could include loggedInUserId and dailyPromptId and it would initialize the view from that. 
Just a note, the loggedInUserId is needed for ProfileView and dailyPromptId is needed for FeedView.

### CODE REVIEW

**Review by momoasalu — COMMENTED** [review]
Hey Haya! Great job on solving the dependency rule! 
This looks fine but you should be using the facade and delegating from there instead of casting the data access object type. Also I’m not sure when you last pulled from main on this branch but I did already add a logged in user to the user data access object.

I’m also not sure why you changed the type in response from song ID to song? It’s probably just easier to store a song when you create a response. It might be slower to call the API every time you need the song information.

**Comment by hayatariq** [comment]
Also in response class i changed it from song to songId. unless you are talking about another class i am not sure what you are talking about.

**Comment by hayatariq** [comment]
and i requested to pull the main code so i can use the facade!

**Comment by hayatariq** [comment]
ohh you mean why I changed it from song to songId? it was just so i can not use the class in the view, i'll see if i can make it a song object.

**Comment by hayatariq** [comment]
okay i changed it back to song!

**Review by NimratGrewal — APPROVED** [review]

**Pull request merged**
