### PR TITLE
Haya

### PR DESCRIPTION
**Pull request by hayatariq**
This is my toFeed toProfile use cases: A few things that still need to be done is fixing consistencies across the whole code. My viewmodels as they stand now do not extend from ViewModel yet. 
The tabs are seen in BaseView. Let me know if you have any questions, thanks!

### CODE REVIEW

**Review by momoasalu — COMMENTED** [review]
Hey! This looks pretty good but I noticed a violation of the dependency rule in your states. Nothing in the interface adapters should use any of the entities directly. I think you should get whatever relevant info you need (stuff you're going to display on the page)from the objects in the use case interactor and put that in a list or a map.

**Comment by hayatariq** [comment]
Ooooh you're right! I'll get on that now

**Comment by hayatariq** [comment]
Should I make a response dao you think? im a little lost as to how i would get the response from the response id?

**Comment by momoasalu** [comment]
> Should I make a response dao you think? im a little lost as to how i would get the response from the response id?

You could search through each user to find a response that matches the ID. I don't think we need a response DAO.

**Comment by hayatariq** [comment]
gotcha, i'll do that for both user and promptdao for each view

**Review by NimratGrewal — APPROVED** [review]

**Pull request closed without merging**
